name: mlp_proj
channels:
  - defaults
dependencies:
  - pip=19.3.1  
  - python=3.7.6
  - pip:
    - git+https://github.com/bnelo12/pytube.git#pytube
    - pydub
    - google-cloud-storage
    - tensorflow
    - librosa
